### ISSUE TITLE
Inconsistency in parameters in README

### ISSUE THREAD

**Issue by adjkant** [brannondorsey/naive-hashcat#2]
In the following section from the README, HASH_MODE and HASH_TYPE are inconsistent. Not sure which one is valid but may confuse someone trying to use in the future.

---------------------------------------

 ```bash
HASH_FILE=hashcat-3.6.0/examples0.hash POT_FILE=hashcat.pot HASH_MODE=0 ./naive-hashcat.sh
```
....

- `HASH_TYPE` is the hash-type code. It describes the type of hash to be cracked ...

---------------------------------------

PS: Came from Hacker News, not personally a user and know this is small but hope it helps someone in the future. Cool project!

**Comment by brannondorsey** [comment]
Just fixed with 7dc2e3bfd128a4e72dc6e0503d5944c5ab250e45. Thank you for bringing this to my attention! I appreciate it :smile_cat:
