### ISSUE TITLE
Best Dictionary to use

### ISSUE THREAD

**Issue by GautamBose** [brannondorsey/naive-hashcat#7]
Hi there, I'm trying to crack a 1Password hash for a friend. Is the rockyou.txt dictionary the best one to use or are there alternatives that might work better? 

Also is it worth adding words or phrases he thinks might be in the password to the dictionary?

**Comment by brannondorsey** [comment]
Rockyou may be to general for your purposes. There are some great password
lists here:

https://github.com/danielmiessler/SecLists/tree/master/Passwords

If something in there doesn't work, the LinkedIn and Dropbox leaks are both
pretty extensive. Are you using a combination or rule based attack or
simply dictionary? What kind of hardware do you have access to? Are you
running this on a GPU?

I imagine you've run the attack using naive hashcat's default settings and
you didn't crack it, correct?

In answer to your Question about adding words to the list that pertain to
your friends life or words they think they may have used, that is always a
good idea.

**Comment by VyankateshRohokale** [comment]
> Hi there, I'm trying to crack a 1Password hash for a friend. Is the rockyou.txt dictionary the best one to use or are there alternatives that might work better? 
> 
> Also is it worth adding words or phrases he thinks might be in the password to the dictionary? 


See is the password is not  a random password like the commons , for example any number combination or number pattern , and passwords like , hello , hii , donothack, or something like that , rockyou.txt is the best way, but if the password is like "jdifb3874jdnn" something like that , then it's nearly very hard to crack , but nowadays no one uses random password , everyone uses common password , so rockyou.txt is the option
