### ISSUE TITLE
After each iteration (1-2 seconds) naive-hashcat stops and waits for user input

### ISSUE THREAD

**Issue by yeralin** [brannondorsey/naive-hashcat#9]
Hello,

It might be a stupid question. But while I'm trying to run naive-hashcat, it stops after each iteration and prints:
`[s]tatus [p]ause [b]ypass [c]echpoint [q]uit =>`
I'm trying to avoid this problem running `yes b | ./naive-hashcat.sh`

**Comment by brannondorsey** [comment]
Hi there,

Are you sure that the behavior you are observing is actually **stopping** each attack? If memory serves me correctly, that is the standard message printed by hashcat **during** a crack, and it indicates the crack is operating normally, but you as the user have several options to interrupt it or view in-progress information. For instance, pressing "s" during a crack should print information about the current crack. The reason you are seeing several of these messages in succession is that naive-hashcat attempts several separate cracks using different combinations of rules. One of these messages should be printed for each run of the `hashcat` binary.

**Comment by yeralin** [comment]
@brannondorsey is right. I thought that when this message is printed, attack stops which is not true.
